# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes.
# Open the launch configuration palette to access and open any launch configuration.
#
# This file defines your launch configuration.
# More on how to do so here:
# https://docs.warp.dev/features/session-management/launch-configurations
#
# All launch configurations are stored under ~/.warp/launch_configurations.
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .

---
name: Start Config
windows:
  - tabs:
      - layout:
          cwd: /Users/alexeyprudkin
          color: blue
      - title: startup
        layout:
          split_direction: horizontal
          panes:
            - cwd: /Users/alexeyprudkin
              commands:
                - exec: brew upgrade
                - exec: datetime=$(date '+%Y-%m-%d %H%M')
                - exec: mkdir ~/Backup/db_remote/"$datetime"
                - exec: scp -r -i ~/.ssh/digital-mers 'root@146.190.119.157:~/example_bot/storage/*' ~/Backup/db_remote/"$datetime"
            - cwd: /Users/alexeyprudkin
              commands:
                - exec: htop
        color: green

